@url = http://localhost:1234

### POST - Crear Rectángulo
POST {{url}}/rectangulos/base-altura
Content-Type: application/json

{
    "base": 10.5,
    "altura": 5.2
}

### POST - Crear Cuadrado
POST {{url}}/rectangulos/cuadrado
Content-Type: application/json

{
    "lado": 9.3 
}

### POST - Lado Inválido
POST {{url}}/rectangulos/cuadrado
Content-Type: application/json

{
    "lado": -5 
}

### POST - Datos Inválidos
POST {{url}}/rectangulos/base-altura
Content-Type: application/json

{
    "base": -5,
    "altura": 10
}

# ---  MODIFICAR RECTÁNGULO ---

### PUT - Modificar Rectángulo
PUT {{url}}/rectangulos/base-altura/1
Content-Type: application/json

{
    "base": 15,
    "altura": 3
}

### PUT - ID Inválido
PUT {{url}}/rectangulos/base-altura/cincuenta
Content-Type: application/json

{
    "base": 10,
    "altura": 10
}

### GET - Listado Completo
GET {{url}}/rectangulos/muestra
