@url = http://localhost:1234/alumnos

# --- CREAR REGISTRO (POST) ---

### POST - Registrar Notas
POST {{url}}/notas
Content-Type: application/json

{
    "alumno": "Juan Perez",
    "id_materia": 1,
    "nota1": 8.5,
    "nota2": 7.0,
    "note3": 9.5
}

# REGISTRO 2: Alumno B en Materia 2
### POST - Registrar Notas 
POST {{url}}/notas
Content-Type: application/json

{
    "alumno": "Maria Lopez",
    "id_materia": 2,
    "nota1": 10.0,
    "nota2": 9.0,
    "note3": 8.0
}

# REGISTRO 3: Alumno A en Materia DIFERENTE (pasa)
### POST - Alumno en otra Materia 
POST {{url}}/notas
Content-Type: application/json

{
    "alumno": "Juan Perez",
    "id_materia": 3,
    "nota1": 6.0,
    "nota2": 6.0,
    "note3": 6.0
}


### POST - Intentar registro duplicado
POST {{url}}/notas
Content-Type: application/json

{
    "alumno": "Juan Perez",
    "id_materia": 1,
    "nota1": 1.0,
    "nota2": 1.0,
    "note3": 1.0
}

### POST - Datos inválidos
POST {{url}}/notas
Content-Type: application/json

{
    "alumno": "",              
    "id_materia": 0,           
    "nota1": 11,               
    "nota2": "Texto",
    "note3": 5
}

# --- CONSULTAR REGISTROS (GET) ---

### GET - Listado Completo (Muestra nombre de materia y promedio)
GET {{url}}/notas

# --- MODIFICAR REGISTRO (PUT) ---

### PUT - Modificar Notas y Nombre
PUT {{url}}/notas/1
Content-Type: application/json

{
    "alumno": "Juan Carlos Perez",
    "id_materia": 1,
    "nota1": 9.0,
    "nota2": 9.0,
    "note3": 9.0
}

# Intentar modificar el Registro 2 para que sea igual al Registro 3 (devuelve 409 Conflict)
### PUT - Conflicto
PUT {{url}}/notas/2
Content-Type: application/json

{
    "alumno": "Juan Carlos Perez",
    "id_materia": 3,
    "nota1": 10,
    "nota2": 10,
    "note3": 10
}